[package]
name = "ProcesadorComprobantes"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.53.1", features = ["rt-multi-thread", "macros"] }
anyhow = "1.0.104"
chrono = "0.4.45"
quick-xml = { version = "0.42.0", features = ["serialize"] }
reqwest = { version = "0.13.5", default-features = false, features = [
  "rustls",
] }
rust_decimal = { version = "1.43.0", features = ["serde-with-str"] }
serde = { version = "1.0.229", features = ["derive"] }
serde_path_to_error = "0.1.20"
